name: Deploy uni-app to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12'
    
    - name: Change to front-end directory
      run: cd kittybook-cli

    - name: Create package.json
      run: npm init -y

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build:h5

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist/build/h5
